version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    working_directory: ~/repo
    steps:
    - checkout
    - run: yarn install
    - run:
        name: Setup Code Climate test reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
    - run:
        name: Tests with coverage
        command: |
          ./cc-test-reporter before-build
          yarn coverage
          ./cc-test-reporter after-build --id $CC_TEST_REPORTER_ID --exit-code $?
    # - run:
    #     name: yarn install for storybooks
    #     command: |
    #       yarn build
    #       cd stories
    #       yarn
    # - run:
    #     name: Tests with coverage for storybooks
    #     command: |
    #       cd stories
    #       yarn test
    # - run:
    #     name: Deploy storybooks to github
    #     command: |
    #       cd stories
    #       yarn build-storybook
    #       yarn deploy-storybook --ci
